version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/db
    env_file:
      - .env
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    container_name: angular_frontend
    restart: always
    ports:
      - "80:80"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
