# Generated by Django 5.1.3 on 2024-11-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_language',
            field=models.CharField(choices=[('english', 'English'), ('french', 'French'), ('camfranglais', 'Camfranglais'), ('pidgin', 'Pidgin')], max_length=50),
        ),
    ]
