# Generated by Django 5.1.3 on 2024-12-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_primary_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='vote_weight',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='vote_weight',
        ),
        migrations.RemoveField(
            model_name='linguist',
            name='vote_weight',
        ),
        migrations.AddField(
            model_name='user',
            name='vote_weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
