# Generated by Django 5.1.3 on 2024-11-28 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('votes', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=50)),
                ('meaning_fr', models.TextField(blank=True, null=True)),
                ('meaning_en', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.component')),
                ('word_name', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('lang_definition', models.CharField(max_length=50)),
            ],
            bases=('dictionary.component',),
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.component')),
                ('ex', models.CharField(max_length=255)),
                ('words', models.ManyToManyField(related_name='expressions', to='dictionary.word')),
            ],
            bases=('dictionary.component',),
        ),
    ]
