# Generated by Django 5.1.3 on 2024-12-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_rename_ex_expression_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='example',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
