# Generated by Django 5.1.3 on 2024-12-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_word_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='component',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
