# Generated by Django 5.1.3 on 2024-12-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_dislike_star'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expression',
        ),
    ]
